import { NextResponse } from "next/server";

async function fetchWithRetry(url: string, options: RequestInit, retries = 3): Promise<Response> {
  for (let i = 0; i < retries; i++) {
    const response = await fetch(url, options);
    if (response.status === 429) {
      const waitTime = 5000 * Math.pow(2, i);
      console.log(`Rate limited. Retrying in ${waitTime / 1000}s... (attempt ${i + 1}/${retries})`);
      await new Promise((resolve) => setTimeout(resolve, waitTime));
      continue;
    }
    return response;
  }
  return fetch(url, options);
}

export async function POST(req: Request) {
  try {
    const { idea, audience, platform, style, features, colorMood } = await req.json();

    const apiKey = process.env.OPENROUTER_API_KEY;

    if (!apiKey) {
      return NextResponse.json({ text: "Server error: API key not configured." });
    }

    const contextParts = [
      `Project idea: ${idea}`,
      audience ? `Target audience: ${audience}` : "",
      platform ? `Platform: ${platform}` : "",
      style ? `Design style: ${style}` : "",
      features?.length ? `Key features: ${features.join(", ")}` : "",
      colorMood ? `Color mood: ${colorMood}` : "",
    ].filter(Boolean).join("\n");

    const systemPrompt = `You are DesignPilot AI — the world's most opinionated UI/UX prompt engineer. You don't generate average prompts. You generate prompts so specific, so detailed, and so design-forward that the resulting UI looks like it was built by a senior designer at a top tech company — not generated by AI.

YOUR GOLDEN RULES:
- Never suggest generic colors like "blue" or "gray" — always give exact hex codes
- Never say "modern design" or "clean UI" — these are meaningless. Be specific.
- Every component must have exact measurements, colors, and behavior described
- Typography must include exact font names, weights, and sizes
- Animations must be described with exact timing and easing
- The output must feel like it was designed by a human with strong opinions

USER'S PROJECT CONTEXT:
${contextParts}

BASED ON THEIR CONTEXT, generate a prompt that feels custom-tailored — not templated. Reference their specific idea, audience, and features directly. Make design decisions that actually make sense for their use case:
- Students → friendly typography, approachable colors, clear hierarchy
- Businesses → trustworthy palette, structured layout, professional tone
- Dark mode → rich deep backgrounds like #0D1117 or #0A0A0F, not just black
- Glassmorphism → specify exact backdrop-filter values, border opacity, blur amounts

FORMAT YOUR RESPONSE EXACTLY LIKE THIS — no extra text before or after:

PROMPT_START
[Write the complete prompt as a direct instruction starting with "Build a..." or "Create a...". Be obsessively specific. Include:
- Exact color palette with hex codes (minimum 5 colors)
- Typography: font family, weights, sizes for headings/body/labels
- Layout: exact grid structure, spacing values, max-width
- Navigation: type, items, mobile behavior, scroll behavior
- Hero section: exact layout, headline style, CTA design
- Every key component with specific styles, hover states, animations
- Responsive breakpoints with specific behavior changes
- Micro-interactions with exact timing like "0.2s ease" or "0.4s cubic-bezier(0.16, 1, 0.3, 1)"
- Unique design details that make this feel handcrafted, not AI-generated]
PROMPT_END

DESIGN_BRIEF_START
Layout: [Specific layout approach for this exact project]
Navigation: [Specific nav recommendation for this audience and platform]
Design: [Specific color and typography rationale tied to their use case]
Components: [The 3-4 most important components and why they matter for this project]
Responsive: [Specific responsive strategy for their platform choice]
DESIGN_BRIEF_END`;

    const freeModels = [
      "nvidia/nemotron-nano-9b-v2:free",
      "meta-llama/llama-3.1-8b-instruct:free",
      "google/gemma-2-9b-it:free",
    ];

    let data = null;
    let response = null;

    for (const model of freeModels) {
      console.log(`Trying model: ${model}`);
      response = await fetchWithRetry(
        "https://openrouter.ai/api/v1/chat/completions",
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${apiKey}`,
            "Content-Type": "application/json",
            "HTTP-Referer": "https://designpilot-taupe.vercel.app",
            "X-Title": "DesignPilot AI",
          },
          body: JSON.stringify({
            model,
            messages: [
              { role: "system", content: systemPrompt },
              { role: "user", content: contextParts },
            ],
          }),
        }
      );

      data = await response.json();
      console.log(`API RESPONSE STATUS for ${model}:`, response.status);

      if (response.status === 429 || data.error) {
        console.log(`Model ${model} failed, trying next...`);
        await new Promise((resolve) => setTimeout(resolve, 2000));
        continue;
      }

      break; // success
    }

    if (!data || !response) {
      return NextResponse.json({ text: "All models failed. Please try again in 60 seconds." });
    }

    if (response.status === 429) {
      return NextResponse.json({
        text: "Rate limited by OpenRouter. Please wait 60 seconds and try again.",
      });
    }

    if (data.error) {
      return NextResponse.json({
        text: `API Error: ${data.error.message || "Unknown error from OpenRouter"}`,
      });
    }

    const fullText = data?.choices?.[0]?.message?.content || "";

    // Parse the structured output
    const promptMatch = fullText.match(/PROMPT_START\s*([\s\S]*?)\s*PROMPT_END/);
    const briefMatch = fullText.match(/DESIGN_BRIEF_START\s*([\s\S]*?)\s*DESIGN_BRIEF_END/);

    const prompt = promptMatch ? promptMatch[1].trim() : fullText;
    const brief = briefMatch ? briefMatch[1].trim() : "";

    return NextResponse.json({
      text: fullText,
      prompt,
      brief,
    });

  } catch (error) {
    console.error("FETCH ERROR:", error);
    return NextResponse.json({ text: "Error generating response" });
  }
}